apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: go-hello
  namespace: go-hello
spec:
  minReplicaCount: 1
  maxReplicaCount: 10
  pollingInterval: 60
  cooldownPeriod: 60
  scaleTargetRef:
    name: go-hello
  triggers:
  - type: memory
    metricType: AverageValue
    metadata:
      value: "60"