apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-hello
spec:
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: go-hello
  template:
    metadata:
      labels:
        app: go-hello
    spec:
      containers:
      - image: sergio21/go-hello:0.0.1
        name: go-hello
        resources:
          requests:
            memory: 50Mi
            cpu: 5m
          limits:
            memory: 100Mi
            cpu: 10m
        ports:
        - containerPort: 8080
